export default {
    canvasW: 1140,
    canvasH: 600,
    scale: 20,
    growth: 4,
    gameSpeed: 20,
    initSnakeX: 4,
    initSnakeY: 2,
    initSnakeLen: 3,
    headX: 0,
    headY: 0,
    initSnakeTail: [
        {x:0, y:-100},
        {x:0, y:-100},
        {x:0, y:-100},
    ],
    tail: [],
    AppleX: 160,
    AppleY: 160,
    xSpeed: 1,
    ySpeed: 0,
    direction: "r",
    gameOver: false,
    isRunning: false,
}